[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["chmod +x ./node_modules/.bin/react-scripts && ./node_modules/.bin/react-scripts build"]

[start]
cmd = "npx serve -s build -l $PORT"
