[phases.install]
cmds = ["npm install --legacy-peer-deps && chmod +x node_modules/.bin/react-scripts"]

[phases.build]
cmds = ["./node_modules/.bin/react-scripts build"]

[start]
cmd = "npx serve -s build -l $PORT"
